### ISSUE TITLE
Image and file option in Redactor are not available

### ISSUE THREAD

**Issue by lukwi** [TypeRocket/core#87]
Hey Kevin,

i set the button array for Redactor like in the Documentation, but image and file options are not available, everything else i can enable and disable.
Is there another point, where i have to enable this features or is it not implemented?

Greetings,

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

Unfortunately, v4 is using a very old version of redactor and so we have not integrated the image selector into it. However, if you get TypeRocket Pro it has that feature because we were able to get the latest redactor OEM version for Pro.

If you like you can get the latest version of Redactor for your projects and replace the old one in v4 but it would probably be easier to just get Pro.

Redactor: https://imperavi.com/redactor/buy/
TypeRocket Pro: https://typerocket.com/

Thanks,
Kevin

**Comment by lukwi** [comment]
Okay, i'll think about it and discuss it with the project manager.
How does the single license work? Do i have to pay 59 $ every year as long the Website is running? Or what happens, if the license will be canceled?

Thank you for the support,

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

Your site and the plugin will keep working if you do not renew. Only automatic updates and support will expire for that license. 

Note, upgrading from v4 to Pro will take a bit of work so if you are close to the end of your project it might not want to take that approach. However, I'd like to think Pro is 100% worth it in terms of new features.

**Comment by lukwi** [comment]
Hey Kevin,

a little bit late, i had to work on a few requests.

The project is nearly done. I have solved this image problem with page builder elements.
The authors working with the site like it very much! Much easier than these complex page builders :)

For the next project i will try the pro version!

One last question: Is it possible to enable post revisions for pages using the type rocket page builder and for custom post types?
I tried this in the app config file:

'features' => [
        'post_revisions' => true
    ]

But it doesn't take effect.

Greetings from Germany,

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

TypeRocket uses post meta for the builder field. You would need to find a plugin that gives you revisions for post meta to achieve what you are asking. I've looked at building out such a feature for Pro but I have not been able to get the effect to the level of stability I want. I'm not sure any plugins have done this either but maybe they have been able to figure this feature out.

The alternative option is to update the page builder plugin to use the `post_content` table column instead of post meta.

Thanks,
Kevin

**Comment by lukwi** [comment]
Hey Kevin,

thanks again for your support. What is the disadvantage to update the page builder to use post_content table? Why is it not standard? If i want to do this, i have to do it by modifying the plugin on my own or is there a simple way? I can't find something about this in the documentation.. 

Greetings and health,

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

I would try modifying the plugin. 

The post_content table was not designed to store JSON or serialized data, this is the reason we have not made the page builder in that way. Also, some people may want to use the standard editor alongside the page builder, this is also why we have the builders data saved to meta.

Thanks,
Kevin
