### ISSUE TITLE
Usage in public plugins

### ISSUE THREAD

**Issue by alessandrotesoro** [TypeRocket/core#88]
Hi there,

Apologies if this isn't the right place to get in touch about this. I couldn't find a contact page on the TypeRocket website.

I've read this page https://typerocket.com/how-to-use-and-install-typerocket/ and I understand you guys discourage usage of the framework if I don't have control of the website due to potential collisions. 

Would it be possible to use typerocket is a public plugin that would be distributed through WordPress.org but only after using this https://github.com/humbug/php-scoper ? 

I'm developing a very complex plugin and I believe your framework is the only way to make the development experience wonderful.

Please let me know.

Regards.

**Comment by kevindees** [comment]
Hey @alessandrotesoro 

Glad to help. Unfortunately, I'm not sure it will be that simple but maybe it will be.

If you scope things in v4 Open be sure to also update the js and CSS prefixes. Also, be sure to update any functions and hook names (actions and filters) that start with `tr_` or 'typerocket'.

With Pro, we ask that you have your plugin use Pro as a dependency instead of building it into your project files.

Thanks,
Kevin

**Comment by alessandrotesoro** [comment]
Hey @kevindees 

Thanks a lot for your reply. My intention is to use TypeRocket Pro as a composer dependency ( I wouldn't do it any other way) to help build the plugin I'm working on. The plugin will then be released on wp.org.

I don't think scoper changes anything in regards to html output so I'm guessing that css and js should be fine.

It would seem that PHP Scoper takes care of global functions too, so functions with tr_ prefix should be somehow taken care of ( I don't know all the details yet ). It seems it's getting more popular in the WP ecosystem https://deliciousbrains.com/php-scoper-namespace-composer-depencies/ 

For a publicly available plugin, which license would I need? Single, plus or max?

Thank you.
